/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnomalyAction = { 'Flag' : null } |
  { 'Alert' : null };
export interface AnomalyRule {
  'id' : AnomalyRuleId,
  'action' : AnomalyAction,
  'threshold' : number,
  'name' : string,
  'entityType' : EntityType,
}
export type AnomalyRuleId = bigint;
export interface Attribute { 'key' : string, 'value' : string }
export interface DataSource {
  'id' : DataSourceId,
  'status' : DataSourceStatus,
  'name' : string,
  'sourceType' : DataSourceType,
  'syncHistory' : Array<SyncRecord>,
  'config' : DataSourceConfig,
  'lastSync' : [] | [Timestamp],
  'recordCount' : bigint,
}
export interface DataSourceConfig {
  'url' : string,
  'headers' : Array<[string, string]>,
  'intervalSeconds' : bigint,
}
export type DataSourceId = bigint;
export type DataSourceStatus = { 'Error' : null } |
  { 'Idle' : null } |
  { 'Connected' : null } |
  { 'Syncing' : null };
export type DataSourceType = { 'CSV' : null } |
  { 'REST_API' : null } |
  { 'JSON_Feed' : null };
export interface Entity {
  'id' : EntityId,
  'name' : string,
  'lastUpdated' : Timestamp,
  'sourceId' : [] | [DataSourceId],
  'attributes' : Array<Attribute>,
  'entityType' : EntityType,
  'relationships' : Array<Relationship>,
}
export type EntityId = bigint;
export type EntityType = { 'Event' : null } |
  { 'Person' : null } |
  { 'Organization' : null } |
  { 'Asset' : null };
export interface Incident {
  'id' : IncidentId,
  'status' : IncidentStatus,
  'title' : string,
  'relatedEntityIds' : Array<EntityId>,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'notes' : string,
  'severity' : Severity,
  'timeline' : Array<TimelineEvent>,
}
export type IncidentId = bigint;
export type IncidentStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'Investigating' : null };
export interface Investigation {
  'id' : InvestigationId,
  'name' : string,
  'createdAt' : Timestamp,
  'entityIds' : Array<EntityId>,
}
export type InvestigationId = bigint;
export interface Relationship {
  'targetId' : EntityId,
  'relationshipType' : string,
}
export type Severity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface SyncRecord {
  'status' : DataSourceStatus,
  'message' : string,
  'timestamp' : Timestamp,
  'recordCount' : bigint,
}
export interface TimelineEvent {
  'note' : string,
  'timestamp' : Timestamp,
  'eventType' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnomalyRule' : ActorMethod<
    [string, EntityType, number, AnomalyAction],
    AnomalyRule
  >,
  'addDataSource' : ActorMethod<
    [string, DataSourceType, DataSourceConfig],
    DataSource
  >,
  'addEntity' : ActorMethod<
    [
      string,
      EntityType,
      Array<Attribute>,
      Array<Relationship>,
      [] | [DataSourceId],
    ],
    Entity
  >,
  'addIncident' : ActorMethod<
    [string, string, Severity, Array<EntityId>],
    Incident
  >,
  'addIncidentEvent' : ActorMethod<[IncidentId, string, string], boolean>,
  'deleteAnomalyRule' : ActorMethod<[AnomalyRuleId], boolean>,
  'deleteDataSource' : ActorMethod<[DataSourceId], boolean>,
  'deleteEntity' : ActorMethod<[EntityId], boolean>,
  'deleteIncident' : ActorMethod<[IncidentId], boolean>,
  'deleteInvestigation' : ActorMethod<[InvestigationId], boolean>,
  'getAnomalyRule' : ActorMethod<[AnomalyRuleId], [] | [AnomalyRule]>,
  'getDataSource' : ActorMethod<[DataSourceId], [] | [DataSource]>,
  'getEntity' : ActorMethod<[EntityId], [] | [Entity]>,
  'getIncident' : ActorMethod<[IncidentId], [] | [Incident]>,
  'getInvestigation' : ActorMethod<[InvestigationId], [] | [Investigation]>,
  'getSyncHistory' : ActorMethod<[DataSourceId], [] | [Array<SyncRecord>]>,
  'listAnomalyRules' : ActorMethod<[], Array<AnomalyRule>>,
  'listDataSources' : ActorMethod<[], Array<DataSource>>,
  'listEntities' : ActorMethod<[], Array<Entity>>,
  'listIncidents' : ActorMethod<[], Array<Incident>>,
  'listInvestigations' : ActorMethod<[], Array<Investigation>>,
  'saveInvestigation' : ActorMethod<[string, Array<EntityId>], Investigation>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerDataSourceSync' : ActorMethod<[DataSourceId], string>,
  'updateAnomalyRule' : ActorMethod<
    [AnomalyRuleId, string, EntityType, number, AnomalyAction],
    boolean
  >,
  'updateDataSource' : ActorMethod<
    [DataSourceId, string, DataSourceConfig],
    boolean
  >,
  'updateDataSourceSync' : ActorMethod<
    [DataSourceId, DataSourceStatus, bigint, string],
    boolean
  >,
  'updateEntity' : ActorMethod<
    [EntityId, string, EntityType, Array<Attribute>, Array<Relationship>],
    boolean
  >,
  'updateIncident' : ActorMethod<
    [IncidentId, string, string, Severity, IncidentStatus, string],
    boolean
  >,
  'updateInvestigation' : ActorMethod<
    [InvestigationId, string, Array<EntityId>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];