/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EntityType = IDL.Variant({
  'Event' : IDL.Null,
  'Person' : IDL.Null,
  'Organization' : IDL.Null,
  'Asset' : IDL.Null,
});
export const AnomalyAction = IDL.Variant({
  'Flag' : IDL.Null,
  'Alert' : IDL.Null,
});
export const AnomalyRuleId = IDL.Nat;
export const AnomalyRule = IDL.Record({
  'id' : AnomalyRuleId,
  'action' : AnomalyAction,
  'threshold' : IDL.Float64,
  'name' : IDL.Text,
  'entityType' : EntityType,
});
export const DataSourceType = IDL.Variant({
  'CSV' : IDL.Null,
  'REST_API' : IDL.Null,
  'JSON_Feed' : IDL.Null,
});
export const DataSourceConfig = IDL.Record({
  'url' : IDL.Text,
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'intervalSeconds' : IDL.Nat,
});
export const DataSourceId = IDL.Nat;
export const DataSourceStatus = IDL.Variant({
  'Error' : IDL.Null,
  'Idle' : IDL.Null,
  'Connected' : IDL.Null,
  'Syncing' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SyncRecord = IDL.Record({
  'status' : DataSourceStatus,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'recordCount' : IDL.Nat,
});
export const DataSource = IDL.Record({
  'id' : DataSourceId,
  'status' : DataSourceStatus,
  'name' : IDL.Text,
  'sourceType' : DataSourceType,
  'syncHistory' : IDL.Vec(SyncRecord),
  'config' : DataSourceConfig,
  'lastSync' : IDL.Opt(Timestamp),
  'recordCount' : IDL.Nat,
});
export const Attribute = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const EntityId = IDL.Nat;
export const Relationship = IDL.Record({
  'targetId' : EntityId,
  'relationshipType' : IDL.Text,
});
export const Entity = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'lastUpdated' : Timestamp,
  'sourceId' : IDL.Opt(DataSourceId),
  'attributes' : IDL.Vec(Attribute),
  'entityType' : EntityType,
  'relationships' : IDL.Vec(Relationship),
});
export const Severity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const IncidentId = IDL.Nat;
export const IncidentStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'Investigating' : IDL.Null,
});
export const TimelineEvent = IDL.Record({
  'note' : IDL.Text,
  'timestamp' : Timestamp,
  'eventType' : IDL.Text,
});
export const Incident = IDL.Record({
  'id' : IncidentId,
  'status' : IncidentStatus,
  'title' : IDL.Text,
  'relatedEntityIds' : IDL.Vec(EntityId),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'severity' : Severity,
  'timeline' : IDL.Vec(TimelineEvent),
});
export const InvestigationId = IDL.Nat;
export const Investigation = IDL.Record({
  'id' : InvestigationId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'entityIds' : IDL.Vec(EntityId),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnomalyRule' : IDL.Func(
      [IDL.Text, EntityType, IDL.Float64, AnomalyAction],
      [AnomalyRule],
      [],
    ),
  'addDataSource' : IDL.Func(
      [IDL.Text, DataSourceType, DataSourceConfig],
      [DataSource],
      [],
    ),
  'addEntity' : IDL.Func(
      [
        IDL.Text,
        EntityType,
        IDL.Vec(Attribute),
        IDL.Vec(Relationship),
        IDL.Opt(DataSourceId),
      ],
      [Entity],
      [],
    ),
  'addIncident' : IDL.Func(
      [IDL.Text, IDL.Text, Severity, IDL.Vec(EntityId)],
      [Incident],
      [],
    ),
  'addIncidentEvent' : IDL.Func(
      [IncidentId, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteAnomalyRule' : IDL.Func([AnomalyRuleId], [IDL.Bool], []),
  'deleteDataSource' : IDL.Func([DataSourceId], [IDL.Bool], []),
  'deleteEntity' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteIncident' : IDL.Func([IncidentId], [IDL.Bool], []),
  'deleteInvestigation' : IDL.Func([InvestigationId], [IDL.Bool], []),
  'getAnomalyRule' : IDL.Func(
      [AnomalyRuleId],
      [IDL.Opt(AnomalyRule)],
      ['query'],
    ),
  'getDataSource' : IDL.Func([DataSourceId], [IDL.Opt(DataSource)], ['query']),
  'getEntity' : IDL.Func([EntityId], [IDL.Opt(Entity)], ['query']),
  'getIncident' : IDL.Func([IncidentId], [IDL.Opt(Incident)], ['query']),
  'getInvestigation' : IDL.Func(
      [InvestigationId],
      [IDL.Opt(Investigation)],
      ['query'],
    ),
  'getSyncHistory' : IDL.Func(
      [DataSourceId],
      [IDL.Opt(IDL.Vec(SyncRecord))],
      ['query'],
    ),
  'listAnomalyRules' : IDL.Func([], [IDL.Vec(AnomalyRule)], ['query']),
  'listDataSources' : IDL.Func([], [IDL.Vec(DataSource)], ['query']),
  'listEntities' : IDL.Func([], [IDL.Vec(Entity)], ['query']),
  'listIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'listInvestigations' : IDL.Func([], [IDL.Vec(Investigation)], ['query']),
  'saveInvestigation' : IDL.Func(
      [IDL.Text, IDL.Vec(EntityId)],
      [Investigation],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerDataSourceSync' : IDL.Func([DataSourceId], [IDL.Text], []),
  'updateAnomalyRule' : IDL.Func(
      [AnomalyRuleId, IDL.Text, EntityType, IDL.Float64, AnomalyAction],
      [IDL.Bool],
      [],
    ),
  'updateDataSource' : IDL.Func(
      [DataSourceId, IDL.Text, DataSourceConfig],
      [IDL.Bool],
      [],
    ),
  'updateDataSourceSync' : IDL.Func(
      [DataSourceId, DataSourceStatus, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateEntity' : IDL.Func(
      [
        EntityId,
        IDL.Text,
        EntityType,
        IDL.Vec(Attribute),
        IDL.Vec(Relationship),
      ],
      [IDL.Bool],
      [],
    ),
  'updateIncident' : IDL.Func(
      [IncidentId, IDL.Text, IDL.Text, Severity, IncidentStatus, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateInvestigation' : IDL.Func(
      [InvestigationId, IDL.Text, IDL.Vec(EntityId)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EntityType = IDL.Variant({
    'Event' : IDL.Null,
    'Person' : IDL.Null,
    'Organization' : IDL.Null,
    'Asset' : IDL.Null,
  });
  const AnomalyAction = IDL.Variant({ 'Flag' : IDL.Null, 'Alert' : IDL.Null });
  const AnomalyRuleId = IDL.Nat;
  const AnomalyRule = IDL.Record({
    'id' : AnomalyRuleId,
    'action' : AnomalyAction,
    'threshold' : IDL.Float64,
    'name' : IDL.Text,
    'entityType' : EntityType,
  });
  const DataSourceType = IDL.Variant({
    'CSV' : IDL.Null,
    'REST_API' : IDL.Null,
    'JSON_Feed' : IDL.Null,
  });
  const DataSourceConfig = IDL.Record({
    'url' : IDL.Text,
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'intervalSeconds' : IDL.Nat,
  });
  const DataSourceId = IDL.Nat;
  const DataSourceStatus = IDL.Variant({
    'Error' : IDL.Null,
    'Idle' : IDL.Null,
    'Connected' : IDL.Null,
    'Syncing' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SyncRecord = IDL.Record({
    'status' : DataSourceStatus,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'recordCount' : IDL.Nat,
  });
  const DataSource = IDL.Record({
    'id' : DataSourceId,
    'status' : DataSourceStatus,
    'name' : IDL.Text,
    'sourceType' : DataSourceType,
    'syncHistory' : IDL.Vec(SyncRecord),
    'config' : DataSourceConfig,
    'lastSync' : IDL.Opt(Timestamp),
    'recordCount' : IDL.Nat,
  });
  const Attribute = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const EntityId = IDL.Nat;
  const Relationship = IDL.Record({
    'targetId' : EntityId,
    'relationshipType' : IDL.Text,
  });
  const Entity = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'lastUpdated' : Timestamp,
    'sourceId' : IDL.Opt(DataSourceId),
    'attributes' : IDL.Vec(Attribute),
    'entityType' : EntityType,
    'relationships' : IDL.Vec(Relationship),
  });
  const Severity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const IncidentId = IDL.Nat;
  const IncidentStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'Investigating' : IDL.Null,
  });
  const TimelineEvent = IDL.Record({
    'note' : IDL.Text,
    'timestamp' : Timestamp,
    'eventType' : IDL.Text,
  });
  const Incident = IDL.Record({
    'id' : IncidentId,
    'status' : IncidentStatus,
    'title' : IDL.Text,
    'relatedEntityIds' : IDL.Vec(EntityId),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'severity' : Severity,
    'timeline' : IDL.Vec(TimelineEvent),
  });
  const InvestigationId = IDL.Nat;
  const Investigation = IDL.Record({
    'id' : InvestigationId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'entityIds' : IDL.Vec(EntityId),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnomalyRule' : IDL.Func(
        [IDL.Text, EntityType, IDL.Float64, AnomalyAction],
        [AnomalyRule],
        [],
      ),
    'addDataSource' : IDL.Func(
        [IDL.Text, DataSourceType, DataSourceConfig],
        [DataSource],
        [],
      ),
    'addEntity' : IDL.Func(
        [
          IDL.Text,
          EntityType,
          IDL.Vec(Attribute),
          IDL.Vec(Relationship),
          IDL.Opt(DataSourceId),
        ],
        [Entity],
        [],
      ),
    'addIncident' : IDL.Func(
        [IDL.Text, IDL.Text, Severity, IDL.Vec(EntityId)],
        [Incident],
        [],
      ),
    'addIncidentEvent' : IDL.Func(
        [IncidentId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteAnomalyRule' : IDL.Func([AnomalyRuleId], [IDL.Bool], []),
    'deleteDataSource' : IDL.Func([DataSourceId], [IDL.Bool], []),
    'deleteEntity' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteIncident' : IDL.Func([IncidentId], [IDL.Bool], []),
    'deleteInvestigation' : IDL.Func([InvestigationId], [IDL.Bool], []),
    'getAnomalyRule' : IDL.Func(
        [AnomalyRuleId],
        [IDL.Opt(AnomalyRule)],
        ['query'],
      ),
    'getDataSource' : IDL.Func(
        [DataSourceId],
        [IDL.Opt(DataSource)],
        ['query'],
      ),
    'getEntity' : IDL.Func([EntityId], [IDL.Opt(Entity)], ['query']),
    'getIncident' : IDL.Func([IncidentId], [IDL.Opt(Incident)], ['query']),
    'getInvestigation' : IDL.Func(
        [InvestigationId],
        [IDL.Opt(Investigation)],
        ['query'],
      ),
    'getSyncHistory' : IDL.Func(
        [DataSourceId],
        [IDL.Opt(IDL.Vec(SyncRecord))],
        ['query'],
      ),
    'listAnomalyRules' : IDL.Func([], [IDL.Vec(AnomalyRule)], ['query']),
    'listDataSources' : IDL.Func([], [IDL.Vec(DataSource)], ['query']),
    'listEntities' : IDL.Func([], [IDL.Vec(Entity)], ['query']),
    'listIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'listInvestigations' : IDL.Func([], [IDL.Vec(Investigation)], ['query']),
    'saveInvestigation' : IDL.Func(
        [IDL.Text, IDL.Vec(EntityId)],
        [Investigation],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerDataSourceSync' : IDL.Func([DataSourceId], [IDL.Text], []),
    'updateAnomalyRule' : IDL.Func(
        [AnomalyRuleId, IDL.Text, EntityType, IDL.Float64, AnomalyAction],
        [IDL.Bool],
        [],
      ),
    'updateDataSource' : IDL.Func(
        [DataSourceId, IDL.Text, DataSourceConfig],
        [IDL.Bool],
        [],
      ),
    'updateDataSourceSync' : IDL.Func(
        [DataSourceId, DataSourceStatus, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateEntity' : IDL.Func(
        [
          EntityId,
          IDL.Text,
          EntityType,
          IDL.Vec(Attribute),
          IDL.Vec(Relationship),
        ],
        [IDL.Bool],
        [],
      ),
    'updateIncident' : IDL.Func(
        [IncidentId, IDL.Text, IDL.Text, Severity, IncidentStatus, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateInvestigation' : IDL.Func(
        [InvestigationId, IDL.Text, IDL.Vec(EntityId)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };