/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Investigation {
    id: InvestigationId;
    name: string;
    createdAt: Timestamp;
    entityIds: Array<EntityId>;
}
export type IncidentId = bigint;
export type EntityId = bigint;
export type AnomalyRuleId = bigint;
export type InvestigationId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TimelineEvent {
    note: string;
    timestamp: Timestamp;
    eventType: string;
}
export interface Entity {
    id: EntityId;
    name: string;
    lastUpdated: Timestamp;
    sourceId?: DataSourceId;
    attributes: Array<Attribute>;
    entityType: EntityType;
    relationships: Array<Relationship>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SyncRecord {
    status: DataSourceStatus;
    message: string;
    timestamp: Timestamp;
    recordCount: bigint;
}
export interface AnomalyRule {
    id: AnomalyRuleId;
    action: AnomalyAction;
    threshold: number;
    name: string;
    entityType: EntityType;
}
export interface DataSource {
    id: DataSourceId;
    status: DataSourceStatus;
    name: string;
    sourceType: DataSourceType;
    syncHistory: Array<SyncRecord>;
    config: DataSourceConfig;
    lastSync?: Timestamp;
    recordCount: bigint;
}
export interface DataSourceConfig {
    url: string;
    headers: Array<[string, string]>;
    intervalSeconds: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Incident {
    id: IncidentId;
    status: IncidentStatus;
    title: string;
    relatedEntityIds: Array<EntityId>;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    notes: string;
    severity: Severity;
    timeline: Array<TimelineEvent>;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Attribute {
    key: string;
    value: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type DataSourceId = bigint;
export interface Relationship {
    targetId: EntityId;
    relationshipType: string;
}
export enum AnomalyAction {
    Flag = "Flag",
    Alert = "Alert"
}
export enum DataSourceStatus {
    Error_ = "Error",
    Idle = "Idle",
    Connected = "Connected",
    Syncing = "Syncing"
}
export enum DataSourceType {
    CSV = "CSV",
    REST_API = "REST_API",
    JSON_Feed = "JSON_Feed"
}
export enum EntityType {
    Event = "Event",
    Person = "Person",
    Organization = "Organization",
    Asset = "Asset"
}
export enum IncidentStatus {
    Open = "Open",
    Closed = "Closed",
    Investigating = "Investigating"
}
export enum Severity {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addAnomalyRule(name: string, entityType: EntityType, threshold: number, action: AnomalyAction): Promise<AnomalyRule>;
    addDataSource(name: string, sourceType: DataSourceType, config: DataSourceConfig): Promise<DataSource>;
    addEntity(name: string, entityType: EntityType, attributes: Array<Attribute>, relationships: Array<Relationship>, sourceId: DataSourceId | null): Promise<Entity>;
    addIncident(title: string, description: string, severity: Severity, relatedEntityIds: Array<EntityId>): Promise<Incident>;
    addIncidentEvent(id: IncidentId, eventType: string, note: string): Promise<boolean>;
    deleteAnomalyRule(id: AnomalyRuleId): Promise<boolean>;
    deleteDataSource(id: DataSourceId): Promise<boolean>;
    deleteEntity(id: EntityId): Promise<boolean>;
    deleteIncident(id: IncidentId): Promise<boolean>;
    deleteInvestigation(id: InvestigationId): Promise<boolean>;
    getAnomalyRule(id: AnomalyRuleId): Promise<AnomalyRule | null>;
    getDataSource(id: DataSourceId): Promise<DataSource | null>;
    getEntity(id: EntityId): Promise<Entity | null>;
    getIncident(id: IncidentId): Promise<Incident | null>;
    getInvestigation(id: InvestigationId): Promise<Investigation | null>;
    getSyncHistory(id: DataSourceId): Promise<Array<SyncRecord> | null>;
    listAnomalyRules(): Promise<Array<AnomalyRule>>;
    listDataSources(): Promise<Array<DataSource>>;
    listEntities(): Promise<Array<Entity>>;
    listIncidents(): Promise<Array<Incident>>;
    listInvestigations(): Promise<Array<Investigation>>;
    saveInvestigation(name: string, entityIds: Array<EntityId>): Promise<Investigation>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerDataSourceSync(id: DataSourceId): Promise<string>;
    updateAnomalyRule(id: AnomalyRuleId, name: string, entityType: EntityType, threshold: number, action: AnomalyAction): Promise<boolean>;
    updateDataSource(id: DataSourceId, name: string, config: DataSourceConfig): Promise<boolean>;
    updateDataSourceSync(id: DataSourceId, status: DataSourceStatus, recordCount: bigint, message: string): Promise<boolean>;
    updateEntity(id: EntityId, name: string, entityType: EntityType, attributes: Array<Attribute>, relationships: Array<Relationship>): Promise<boolean>;
    updateIncident(id: IncidentId, title: string, description: string, severity: Severity, status: IncidentStatus, notes: string): Promise<boolean>;
    updateInvestigation(id: InvestigationId, name: string, entityIds: Array<EntityId>): Promise<boolean>;
}
import type { AnomalyAction as _AnomalyAction, AnomalyRule as _AnomalyRule, AnomalyRuleId as _AnomalyRuleId, Attribute as _Attribute, DataSource as _DataSource, DataSourceConfig as _DataSourceConfig, DataSourceId as _DataSourceId, DataSourceStatus as _DataSourceStatus, DataSourceType as _DataSourceType, Entity as _Entity, EntityId as _EntityId, EntityType as _EntityType, Incident as _Incident, IncidentId as _IncidentId, IncidentStatus as _IncidentStatus, Investigation as _Investigation, Relationship as _Relationship, Severity as _Severity, SyncRecord as _SyncRecord, TimelineEvent as _TimelineEvent, Timestamp as _Timestamp, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAnomalyRule(arg0: string, arg1: EntityType, arg2: number, arg3: AnomalyAction): Promise<AnomalyRule> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnomalyRule(arg0, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_AnomalyAction_n10(this._uploadFile, this._downloadFile, arg3));
                return from_candid_AnomalyRule_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnomalyRule(arg0, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_AnomalyAction_n10(this._uploadFile, this._downloadFile, arg3));
            return from_candid_AnomalyRule_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDataSource(arg0: string, arg1: DataSourceType, arg2: DataSourceConfig): Promise<DataSource> {
        if (this.processError) {
            try {
                const result = await this.actor.addDataSource(arg0, to_candid_DataSourceType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_DataSource_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDataSource(arg0, to_candid_DataSourceType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_DataSource_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addEntity(arg0: string, arg1: EntityType, arg2: Array<Attribute>, arg3: Array<Relationship>, arg4: DataSourceId | null): Promise<Entity> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntity(arg0, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Entity_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntity(arg0, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Entity_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async addIncident(arg0: string, arg1: string, arg2: Severity, arg3: Array<EntityId>): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncident(arg0, arg1, to_candid_Severity_n34(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Incident_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncident(arg0, arg1, to_candid_Severity_n34(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Incident_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async addIncidentEvent(arg0: IncidentId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncidentEvent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncidentEvent(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAnomalyRule(arg0: AnomalyRuleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnomalyRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnomalyRule(arg0);
            return result;
        }
    }
    async deleteDataSource(arg0: DataSourceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDataSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDataSource(arg0);
            return result;
        }
    }
    async deleteEntity(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntity(arg0);
            return result;
        }
    }
    async deleteIncident(arg0: IncidentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncident(arg0);
            return result;
        }
    }
    async deleteInvestigation(arg0: InvestigationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvestigation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvestigation(arg0);
            return result;
        }
    }
    async getAnomalyRule(arg0: AnomalyRuleId): Promise<AnomalyRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnomalyRule(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnomalyRule(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataSource(arg0: DataSourceId): Promise<DataSource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataSource(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataSource(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntity(arg0: EntityId): Promise<Entity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntity(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntity(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncident(arg0: IncidentId): Promise<Incident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestigation(arg0: InvestigationId): Promise<Investigation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestigation(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestigation(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSyncHistory(arg0: DataSourceId): Promise<Array<SyncRecord> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyncHistory(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyncHistory(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnomalyRules(): Promise<Array<AnomalyRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnomalyRules();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnomalyRules();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDataSources(): Promise<Array<DataSource>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDataSources();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDataSources();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEntities(): Promise<Array<Entity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEntities();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEntities();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIncidents();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIncidents();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvestigations(): Promise<Array<Investigation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvestigations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvestigations();
            return result;
        }
    }
    async saveInvestigation(arg0: string, arg1: Array<EntityId>): Promise<Investigation> {
        if (this.processError) {
            try {
                const result = await this.actor.saveInvestigation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveInvestigation(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerDataSourceSync(arg0: DataSourceId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerDataSourceSync(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerDataSourceSync(arg0);
            return result;
        }
    }
    async updateAnomalyRule(arg0: AnomalyRuleId, arg1: string, arg2: EntityType, arg3: number, arg4: AnomalyAction): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnomalyRule(arg0, arg1, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_AnomalyAction_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnomalyRule(arg0, arg1, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_AnomalyAction_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateDataSource(arg0: DataSourceId, arg1: string, arg2: DataSourceConfig): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDataSource(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDataSource(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDataSourceSync(arg0: DataSourceId, arg1: DataSourceStatus, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDataSourceSync(arg0, to_candid_DataSourceStatus_n52(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDataSourceSync(arg0, to_candid_DataSourceStatus_n52(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateEntity(arg0: EntityId, arg1: string, arg2: EntityType, arg3: Array<Attribute>, arg4: Array<Relationship>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEntity(arg0, arg1, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEntity(arg0, arg1, to_candid_EntityType_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updateIncident(arg0: IncidentId, arg1: string, arg2: string, arg3: Severity, arg4: IncidentStatus, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncident(arg0, arg1, arg2, to_candid_Severity_n34(this._uploadFile, this._downloadFile, arg3), to_candid_IncidentStatus_n54(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncident(arg0, arg1, arg2, to_candid_Severity_n34(this._uploadFile, this._downloadFile, arg3), to_candid_IncidentStatus_n54(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateInvestigation(arg0: InvestigationId, arg1: string, arg2: Array<EntityId>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvestigation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvestigation(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AnomalyAction_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnomalyAction): AnomalyAction {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_AnomalyRule_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnomalyRule): AnomalyRule {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DataSourceStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataSourceStatus): DataSourceStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DataSourceType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataSourceType): DataSourceType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DataSource_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataSource): DataSource {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_EntityType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityType): EntityType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Entity_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Entity): Entity {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Incident_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Incident): Incident {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SyncRecord_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyncRecord): SyncRecord {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataSourceId]): DataSourceId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnomalyRule]): AnomalyRule | null {
    return value.length === 0 ? null : from_candid_AnomalyRule_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataSource]): DataSource | null {
    return value.length === 0 ? null : from_candid_DataSource_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Entity]): Entity | null {
    return value.length === 0 ? null : from_candid_Entity_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Incident]): Incident | null {
    return value.length === 0 ? null : from_candid_Incident_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Investigation]): Investigation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_SyncRecord>]): Array<SyncRecord> | null {
    return value.length === 0 ? null : from_candid_vec_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnomalyRuleId;
    action: _AnomalyAction;
    threshold: number;
    name: string;
    entityType: _EntityType;
}): {
    id: AnomalyRuleId;
    action: AnomalyAction;
    threshold: number;
    name: string;
    entityType: EntityType;
} {
    return {
        id: value.id,
        action: from_candid_AnomalyAction_n14(_uploadFile, _downloadFile, value.action),
        threshold: value.threshold,
        name: value.name,
        entityType: from_candid_EntityType_n16(_uploadFile, _downloadFile, value.entityType)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DataSourceId;
    status: _DataSourceStatus;
    name: string;
    sourceType: _DataSourceType;
    syncHistory: Array<_SyncRecord>;
    config: _DataSourceConfig;
    lastSync: [] | [_Timestamp];
    recordCount: bigint;
}): {
    id: DataSourceId;
    status: DataSourceStatus;
    name: string;
    sourceType: DataSourceType;
    syncHistory: Array<SyncRecord>;
    config: DataSourceConfig;
    lastSync?: Timestamp;
    recordCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_DataSourceStatus_n22(_uploadFile, _downloadFile, value.status),
        name: value.name,
        sourceType: from_candid_DataSourceType_n24(_uploadFile, _downloadFile, value.sourceType),
        syncHistory: from_candid_vec_n26(_uploadFile, _downloadFile, value.syncHistory),
        config: value.config,
        lastSync: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.lastSync)),
        recordCount: value.recordCount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DataSourceStatus;
    message: string;
    timestamp: _Timestamp;
    recordCount: bigint;
}): {
    status: DataSourceStatus;
    message: string;
    timestamp: Timestamp;
    recordCount: bigint;
} {
    return {
        status: from_candid_DataSourceStatus_n22(_uploadFile, _downloadFile, value.status),
        message: value.message,
        timestamp: value.timestamp,
        recordCount: value.recordCount
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    name: string;
    lastUpdated: _Timestamp;
    sourceId: [] | [_DataSourceId];
    attributes: Array<_Attribute>;
    entityType: _EntityType;
    relationships: Array<_Relationship>;
}): {
    id: EntityId;
    name: string;
    lastUpdated: Timestamp;
    sourceId?: DataSourceId;
    attributes: Array<Attribute>;
    entityType: EntityType;
    relationships: Array<Relationship>;
} {
    return {
        id: value.id,
        name: value.name,
        lastUpdated: value.lastUpdated,
        sourceId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.sourceId)),
        attributes: value.attributes,
        entityType: from_candid_EntityType_n16(_uploadFile, _downloadFile, value.entityType),
        relationships: value.relationships
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IncidentId;
    status: _IncidentStatus;
    title: string;
    relatedEntityIds: Array<_EntityId>;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    notes: string;
    severity: _Severity;
    timeline: Array<_TimelineEvent>;
}): {
    id: IncidentId;
    status: IncidentStatus;
    title: string;
    relatedEntityIds: Array<EntityId>;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    notes: string;
    severity: Severity;
    timeline: Array<TimelineEvent>;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n38(_uploadFile, _downloadFile, value.status),
        title: value.title,
        relatedEntityIds: value.relatedEntityIds,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        notes: value.notes,
        severity: from_candid_Severity_n40(_uploadFile, _downloadFile, value.severity),
        timeline: value.timeline
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Flag: null;
} | {
    Alert: null;
}): AnomalyAction {
    return "Flag" in value ? AnomalyAction.Flag : "Alert" in value ? AnomalyAction.Alert : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Event: null;
} | {
    Person: null;
} | {
    Organization: null;
} | {
    Asset: null;
}): EntityType {
    return "Event" in value ? EntityType.Event : "Person" in value ? EntityType.Person : "Organization" in value ? EntityType.Organization : "Asset" in value ? EntityType.Asset : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Error: null;
} | {
    Idle: null;
} | {
    Connected: null;
} | {
    Syncing: null;
}): DataSourceStatus {
    return "Error" in value ? DataSourceStatus.Error : "Idle" in value ? DataSourceStatus.Idle : "Connected" in value ? DataSourceStatus.Connected : "Syncing" in value ? DataSourceStatus.Syncing : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CSV: null;
} | {
    REST_API: null;
} | {
    JSON_Feed: null;
}): DataSourceType {
    return "CSV" in value ? DataSourceType.CSV : "REST_API" in value ? DataSourceType.REST_API : "JSON_Feed" in value ? DataSourceType.JSON_Feed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
} | {
    Investigating: null;
}): IncidentStatus {
    return "Open" in value ? IncidentStatus.Open : "Closed" in value ? IncidentStatus.Closed : "Investigating" in value ? IncidentStatus.Investigating : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): Severity {
    return "Low" in value ? Severity.Low : "High" in value ? Severity.High : "Medium" in value ? Severity.Medium : "Critical" in value ? Severity.Critical : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SyncRecord>): Array<SyncRecord> {
    return value.map((x)=>from_candid_SyncRecord_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnomalyRule>): Array<AnomalyRule> {
    return value.map((x)=>from_candid_AnomalyRule_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DataSource>): Array<DataSource> {
    return value.map((x)=>from_candid_DataSource_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Entity>): Array<Entity> {
    return value.map((x)=>from_candid_Entity_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Incident>): Array<Incident> {
    return value.map((x)=>from_candid_Incident_n36(_uploadFile, _downloadFile, x));
}
function to_candid_AnomalyAction_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnomalyAction): _AnomalyAction {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DataSourceStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataSourceStatus): _DataSourceStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_DataSourceType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataSourceType): _DataSourceType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_EntityType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): _EntityType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_IncidentStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): _IncidentStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataSourceId | null): [] | [_DataSourceId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnomalyAction): {
    Flag: null;
} | {
    Alert: null;
} {
    return value == AnomalyAction.Flag ? {
        Flag: null
    } : value == AnomalyAction.Alert ? {
        Alert: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataSourceType): {
    CSV: null;
} | {
    REST_API: null;
} | {
    JSON_Feed: null;
} {
    return value == DataSourceType.CSV ? {
        CSV: null
    } : value == DataSourceType.REST_API ? {
        REST_API: null
    } : value == DataSourceType.JSON_Feed ? {
        JSON_Feed: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == Severity.Low ? {
        Low: null
    } : value == Severity.High ? {
        High: null
    } : value == Severity.Medium ? {
        Medium: null
    } : value == Severity.Critical ? {
        Critical: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataSourceStatus): {
    Error: null;
} | {
    Idle: null;
} | {
    Connected: null;
} | {
    Syncing: null;
} {
    return value == DataSourceStatus.Error ? {
        Error_: null
    } : value == DataSourceStatus.Idle ? {
        Idle: null
    } : value == DataSourceStatus.Connected ? {
        Connected: null
    } : value == DataSourceStatus.Syncing ? {
        Syncing: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): {
    Open: null;
} | {
    Closed: null;
} | {
    Investigating: null;
} {
    return value == IncidentStatus.Open ? {
        Open: null
    } : value == IncidentStatus.Closed ? {
        Closed: null
    } : value == IncidentStatus.Investigating ? {
        Investigating: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): {
    Event: null;
} | {
    Person: null;
} | {
    Organization: null;
} | {
    Asset: null;
} {
    return value == EntityType.Event ? {
        Event: null
    } : value == EntityType.Person ? {
        Person: null
    } : value == EntityType.Organization ? {
        Organization: null
    } : value == EntityType.Asset ? {
        Asset: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
